### ISSUE TITLE
First login warning message cause a error

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-js-widget#260]
When user login firstly, console will report a error:
```
invariant.js:44 Uncaught (in promise) Error: Invalid tag: 
    at invariant (http://localhost:8191/index.js:1154:15)
    at validateDangerousTag (http://localhost:8191/index.js:81797:42)
    at new ReactDOMComponent (http://localhost:8191/index.js:81824:3)
    at Object.createInternalComponent (http://localhost:8191/index.js:33614:10)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (http://localhost:8191/index.js:34668:37)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8191/index.js:80801:22)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8191/index.js:80692:21)
    at Object.mountComponent (http://localhost:8191/index.js:7162:35)
    at Object.obj.(anonymous function) [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8598:20)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8191/index.js:80805:34)
```

I find it is caused by calling `alert.danger({message: 'callingSettingsMessages-firstLogin'})`

**Comment by embbnux** [comment]
fixed
