### ISSUE TITLE
Syntax error when generating docs/

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js-widget#336]
```
➜  docs git:(issue-333) yarn run pageGen
yarn run v0.27.5
$ node buildComponentDocPages.js
CallItem
{ SyntaxError: Unexpected token (160:30)
    at Parser.pp.raise (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseMaybeAssign (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:135:10)
    at Parser.pp.parseExprListItem (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:801:16)
    at Parser.parseExprListItem (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:819:24)
    at Parser.pp.parseExprList (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:789:20)
    at Parser.pp.parseSubscripts (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:270:29)
    at Parser.pp.parseExprSubscripts (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:240:17)
    at Parser.pp.parseMaybeUnary (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:163:19) pos: 4686, loc: Position { line: 160, column: 30 } }
ConversationPanel
{ SyntaxError: Unexpected token (117:38)
    at Parser.pp.raise (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseMaybeAssign (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:135:10)
    at Parser.pp.parseExprListItem (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:801:16)
    at Parser.parseExprListItem (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:819:24)
    at Parser.pp.parseExprList (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:789:20)
    at Parser.pp.parseSubscripts (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:270:29)
    at Parser.pp.parseExprSubscripts (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:240:17)
    at Parser.pp.parseMaybeUnary (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:163:19) pos: 3486, loc: Position { line: 117, column: 38 } }
FormattedMessage
Error: No suitable component definition found.
    at parse (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/dist/parse.js:78:9)
    at Object.defaultParse [as parse] (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/dist/main.js:66:30)
    at componentDirNames.forEach (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/buildComponentDocPages.js:26:39)
    at Array.forEach (native)
    at getComponentsList (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/buildComponentDocPages.js:15:21)
    at Object.<anonymous> (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/buildComponentDocPages.js:171:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
MessageItem
{ SyntaxError: Unexpected token (152:38)
    at Parser.pp.raise (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseMaybeAssign (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:135:10)
    at Parser.pp.parseExprListItem (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:801:16)
    at Parser.parseExprListItem (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:819:24)
    at Parser.pp.parseExprList (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:789:20)
    at Parser.pp.parseSubscripts (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:270:29)
    at Parser.pp.parseExprSubscripts (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:240:17)
    at Parser.pp.parseMaybeUnary (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Users/tyler.liu/src/react/ringcentral-js-widget/docs/node_modules/react-docgen/node_modules/babylon/lib/parser/expression.js:112:19) pos: 4604, loc: Position { line: 152, column: 38 } }
Done in 2.78s.
➜  docs git:(issue-333)
```

**Comment by tylerlong** [comment]
It seems that babylon doesn't support `logConversation = async ({ redirect = true, selected, prefill = true }) => {`.  Changing `.babelrc` might fix this issue.

**Comment by embbnux** [comment]
This problem is  caused by `react-docgen`.  It doesn't support parse async function in component code.

**Comment by tylerlong** [comment]
But this line parses without problem: `createSelectedContact = async (entityType) => {`

Have you fired an issue for `react-docgen`?

**Comment by tylerlong** [comment]
I did some tests I found the following both work:

```js
f = async ({a}) = {
}
```

```js
f = ({a = 'b'}) = {
}
```

However the following doesn't work:

```js
f = async ({a = 'b'}) = {
}
```

**Comment by tylerlong** [comment]
Fixed. PR: https://github.com/ringcentral/ringcentral-js-widget/pull/340
